services:
  next-app:
    container_name: nextjs-prod
    build:
      context: ./next
      dockerfile: Dockerfile
    env_file:
      - path: ./next/.env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - strapi-app

  strapi-app:
    container_name: strapi-prod
    build:
      context: ./strapi
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    env_file:
      - path: ./strapi/.env.production
        required: true
    volumes:
      - /data/storage/strapi:/opt/app/public/uploads
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: strapi-db-prod
    ports:
      - "5432:5432"
    env_file:
      - path: ./strapi/.env.production
        required: true
    volumes:
    - /data/storage/postgresql:/var/lib/postgresql/data:rw
    restart: unless-stopped