services:
  next-app:
    container_name: nextjs-prod
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - path: ./next/.env
        required: true
    environment:
      NODE_ENV: production
    depends_on:
      - strapi-app
    restart: unless-stopped

  strapi-app:
    container_name: strapi-prod
    build:
      context: ./strapi
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    env_file:
      - path: ./strapi/.env
        required: true
    volumes:
      - staging-strapi-uploads:/opt/app/public/uploads
    environment:
      NODE_ENV: production
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: strapi-db-prod
    ports:
      - "5432:5432"
    env_file:
      - path: ./strapi/.env
        required: true
    volumes:
      - staging-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  staging-strapi-uploads:
  staging-postgres-data:
