import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getStrapiGlobalData } from "./utils/utils";
import NavBarLink from "./components/sub_components/navBarLink";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getStrapiGlobalData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>{children}</div>
        </body>
    </html>
  );
}
