import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getStrapiGlobalData } from "./utils/utils";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({subsets: ["latin"]});

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	try {
		const globalData = await getStrapiGlobalData();

		// console.dir(globalData, {depth: null});

		const {global} = globalData.data;
		return (
			<html lang="en">
				<body className={inter.className}>
				{
					global
						? <NavBar blocks={global[0]} />
						: <div>No block!</div>
				}
				<div>{children}</div>
				</body>
			</html>
		);
	} catch(error) {
		console.log(`Error: ${error}`);
		return (
		<html lang="en">
			<body className={inter.className}>
				<div>
					<h1>Problem loading global content</h1>
				</div>
			</body>
		</html>
		);
	}
}
