FROM node:22-alpine

RUN apk add --no-cache \
  build-base gcc autoconf automake \
  zlib-dev libpng-dev nasm bash vips-dev git

ENV NODE_ENV=development

WORKDIR /opt/app

COPY package.json package-lock.json ./
RUN npm config set fetch-retries 5 && \
    npm config set fetch-retry-mintimeout 60000 && \
    npm config set fetch-retry-maxtimeout 600000 && \
    npm ci

ENV PATH=/opt/app/node_modules/.bin:$PATH

EXPOSE 1337
CMD ["npm", "run", "develop"]